This is the dataset of Nepal Census 2021..

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("census.csv")

In [3]:
data

,_id,District,Local Level Name,Total family number,Total household number,Total population,Total Male,Total Female
0,1,Taplejung,Aathrai Tribeni Rural Municipality,2869,2735,12288,6005,6283
1,2,Taplejung,Maiwakhola Rural Municipality,2275,2178,10365,5264,5101
2,3,Taplejung,Meringden Rural Municipality,2683,2528,12040,6181,5859
3,4,Taplejung,Mikwakhola Rural Municipality,1862,1792,7991,4000,3991
4,5,Taplejung,Phaktanglung Rural Municipality,2864,2700,11925,6239,5686
...,...,...,...,...,...,...,...,...
748,749,Darchula,Mahakali Municipality,6080,4596,24572,12072,12500
749,750,Darchula,Malikaarjun Rural Municipality,3241,2993,15754,7631,8123
750,751,Darchula,Marma Rural Municipality,3086,2704,15586,7551,8035
751,752,Darchula,Naugad Rural Municipality,3156,2920,16434,7988,8446
752,753,Darchula,Shailyashikhar Municipality,4561,4012,21932,10685,11247

Data Understanding (5 questions)
1. What are the shape (rows & columns), data types, and basic info of the dataset?

In [4]:
data.shape

(753, 8)

our data set have 753 rows and 8 columns

In [5]:
data.columns

Index(['_id', 'District', 'Local Level Name', 'Total family number',
       'Total household number', 'Total population', 'Total Male',
       'Total Female'],
      dtype='object')

these are our columns:

id = id number 

District = Name of the district

Local Level Name = name of the municipality under the district

Total family number = Total number of families

Total household number = total number of houses 

Total population = total number of people

Total Male = total number of male population

Total Female = Total number of female population

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     753 non-null    int64
 1   District                753 non-null    object
 2   Local Level Name        753 non-null    object
 3   Total family number     753 non-null    int64
 4   Total household number  753 non-null    int64
 5   Total population        753 non-null    int64
 6   Total Male              753 non-null    int64
 7   Total Female            753 non-null    int64
dtypes: int64(6), object(2)
memory usage: 47.2+ KB

2. How many unique Districts and Local Levels are there?

In [17]:
data['District'].unique()

array(['Taplejung', 'Panchthar', 'Ilam', 'Jhapa', 'Morang', 'Sunsari',
       'Dhankuta', 'Terhathum', 'Sankhuwasabha', 'Bhojpur', 'Solukhumbu',
       'Okhaldhunga', 'Khotang', 'Udayapur', 'Saptari', 'Siraha',
       'Dhanusa', 'Mahottari', 'Sarlahi', 'Rautahat', 'Bara', 'Parsa',
       'Sindhuli', 'Ramechhap', 'Dolakha', 'Sindhupalchok',
       'Kavrepalanchok', 'Lalitpur', 'Bhaktapur', 'Kathmandu', 'Nuwakot',
       'Rasuwa', 'Dhading', 'Makwanpur', 'Chitawan', 'Gorkha', 'Lamjung',
       'Tanahu', 'Syangja', 'Kaski', 'Manang', 'Mustang', 'Myagdi',
       'Parbat', 'Baglung', 'Nawalparasi East', 'Gulmi', 'Palpa',
       'Nawalparasi West', 'Rupandehi', 'Kapilbastu', 'Arghakhanchi',
       'Pyuthan', 'Rolpa', 'Rukum East', 'Dang', 'Banke', 'Bardiya',
       'Rukum West', 'Salyan', 'Surkhet', 'Dailekh', 'Jajarkot', 'Dolpa',
       'Jumla', 'Kalikot', 'Mugu', 'Humla', 'Bajura', 'Bajhang', 'Achham',
       'Doti', 'Kailali', 'Kanchanpur', 'Dadeldhura', 'Baitadi',
       'Darchula'], dtype=object)

In [15]:
len(data['District'].unique())

77

77 unique districts

In [23]:
data["Local Level Name"].unique()

array(['Aathrai Tribeni Rural Municipality',
       'Maiwakhola Rural Municipality', 'Meringden Rural Municipality',
       'Mikwakhola Rural Municipality', 'Phaktanglung Rural Municipality',
       'Phungling Municipality', 'Sidingba Rural Municipality',
       'Sirijangha Rural Municipality',
       'Pathivara Yangwarak Rural Municipality',
       'Falelung Rural Municipality', 'Falgunanda Rural Municipality',
       'Hilihang Rural Municipality', 'Kummayak Rural Municipality',
       'Miklajung Rural Municipality', 'Phidim Municipality',
       'Tumbewa Rural Municipality', 'Yangwarak Rural Municipality',
       'Chulachuli Rural Municipality', 'Deumai Municipality',
       'Fakphokthum Rural Municipality', 'Illam Municipality',
       'Maijogmai Rural Municipality', 'Mai Municipality',
       'Mangsebung Rural Municipality', 'Rong Rural Municipality',
       'Sandakpur Rural Municipality', 'Suryodaya Municipality',
       'Arjundhara Municipality', 'Barhadashi Rural Municipality',
       'Bhadrapur Municipality', 'Birtamod Municipality',
       'Buddhashanti Rural Municipality', 'Damak Municipality',
       'Gauradhaha Municipality', 'Gauriganj Rural Municipality',
       'Haldibari Rural Municipality', 'Jhapa Rural Municipality',
       'Kachankawal Rural Municipality', 'Kamal Rural Municipality',
       'Kankai Municipality', 'Mechinagar Municipality',
       'Shivasataxi Municipality', 'Belbari Municipality',
       'Biratnagar Metropolitian City', 'Budhiganga Rural Municipality',
       'Dhanpalthan Rural Municipality', 'Gramthan Rural Municipality',
       'Jahada Rural Municipality', 'Kanepokhari Rural Municipality',
       'Katahari Rural Municipality', 'Kerabari Rural Municipality',
       'Letang Municipality', 'Patahrishanishchare Municipality',
       'Rangeli Municipality', 'Ratuwamai Municipality',
       'Sundarharaicha Municipality', 'Sunwarshi Municipality',
       'Uralabari Municipality', 'Barahchhetra Municipality',
       'Barju Rural Municipality', 'Bhokraha Narsing Rural Municipality',
       'Dewanganj Rural Municipality', 'Dharan Sub-Metropolitian City',
       'Duhabi Municipality', 'Gadhi Rural Municipality',
       'Harinagar Rural Municipality', 'Inaruwa Municipality',
       'Itahari Sub-Metropolitian City', 'Koshi Rural Municipality',
       'Ramdhuni Municipality', 'Chaubise Rural Municipality',
       'Chhathar Jorpati Rural Municipality', 'Dhankuta Municipality',
       'Shahidbhumi Rural Municipality', 'Mahalaxmi Municipality',
       'Pakhribas Municipality', 'Sangurigadhi Rural Municipality',
       'Aathrai Rural Municipality', 'Chhathar Rural Municipality',
       'Laligurans Municipality', 'Menchayam Rural Municipality',
       'Myanglung Municipality', 'Phedap Rural Municipality',
       'Bhotkhola Rural Municipality', 'Chainpur Municipality',
       'Chichila Rural Municipality', 'Dharmadevi Municipality',
       'Khandbari Municipality', 'Madi Municipality',
       'Makalu Rural Municipality', 'Panchakhapan Municipality',
       'Sabhapokhari Rural Municipality', 'Silichong Rural Municipality',
       'Aamchowk Rural Municipality', 'Arun Rural Municipality',
       'Bhojpur Municipality', 'Hatuwagadhi Rural Municipality',
       'Pauwadungma Rural Municipality',
       'Ramprasad Rai Rural Municipality',
       'Salpasilichho Rural Municipality', 'Shadananda Municipality',
       'Temkemaiyung Rural Municipality',
       'Thulung Dudhkoshi Rural Municipality',
       'Maapya Dudhkoshi Rural Municipality',
       'Khumbupasanglahmu Rural Municipality',
       'Likhupike Rural Municipality', 'Mahakulung Rural Municipality',
       'Nechasalyan Rural Municipality', 'Solududhakunda Municipality',
       'Sotang Rural Municipality', 'Champadevi Rural Municipality',
       'Chisankhugadhi Rural Municipality',
       'Khijidemba Rural Municipality', 'Likhu Rural Municipality',
       'Manebhanjyang Rural Municipality', 'Molung Rural Municipality',
       'Siddhicharan Municipality', 'Sunkoshi Rural Municipality',
       'Ainselukhark Rural Municipality',
       'Barahapokhari Rural Municipality',
       'Diprung Chuichumma Rural Municipality',
       'Halesi Tuwachung Municipality', 'Jantedhunga Rural Municipality',
       'Kepilasagadhi Rural Municipality', 'Khotehang Rural Municipality',
       'Rawa Besi Rural Municipality',
       'Diktel Rupakot Majhuwagadhi Municipality',
       'Sakela Rural Municipality', 'Belaka Municipality',
       'Chaudandigadhi Municipality', 'Katari Municipality',
       'Rautamai Rural Municipality', 'Limchungbung Rural Municipality',
       'Tapli Rural Municipality', 'Triyuga Municipality',
       'Udayapurgadhi Rural Municipality',
       'Agnisair Krishna Savaran Rural Municipality',
       'Balan Bihul Rural Municipality', 'Rajgadh Rural Municipality',
       'Bishnupur Rural Municipality', 'Bode Barsain Municipality',
       'Chhinnamasta Rural Municipality', 'Dakneshwori Municipality',
       'Hanumannagar Kankalini Municipality', 'Kanchanrup Municipality',
       'Khadak Municipality', 'Mahadeva Rural Municipality',
       'Rajbiraj Municipality', 'Rupani Rural Municipality',
       'Saptakoshi Rural Municipality', 'Shambhunath Municipality',
       'Surunga Municipality', 'Tilathi Koiladi Rural Municipality',
       'Tirahut Rural Municipality', 'Arnama Rural Municipality',
       'Aurahi Rural Municipality', 'Bariyarpatti Rural Municipality',
       'Bhagawanpur Rural Municipality', 'Dhangadhimai Municipality',
       'Golbazar Municipality', 'Kalyanpur Municipality',
       'Karjanha Municipality', 'Lahan Municipality',
       'Laxmipur Patari Rural Municipality', 'Mirchaiya Municipality',
       'Naraha Rural Municipality', 'Nawarajpur Rural Municipality',
       'Sakhuwanankarkatti Rural Municipality', 'Siraha Municipality',
       'Sukhipur Municipality', 'Aaurahi Rural Municipality',
       'Bateshwor Rural Municipality', 'Bideha Municipality',
       'Chhireshwornath Municipality', 'Dhanauji Rural Municipality',
       'Dhanusadham Municipality', 'Ganeshman Charnath Municipality',
       'Hansapur Municipality', 'Janaknandani Rural Municipality',
       'Janakpurdham Sub-Metropolitian City', 'Kamala Municipality',
       'Lakshminiya Rural Municipality', 'Mithila Bihari Municipality',
       'Mithila Municipality',
       'Mukhiyapatti Musarmiya Rural Municipality',
       'Nagarain Municipality', 'Sabaila Municipality',
       'Sahidnagar Municipality', 'Aurahi Municipality',
       'Balwa Municipality', 'Bardibas Municipality',
       'Bhangaha Municipality', 'Ekdanra Rural Municipality',
       'Gaushala Municipality', 'Jaleswor Municipality',
       'Loharpatti Municipality', 'Mahottari Rural Municipality',
       'Manra Siswa Municipality', 'Matihani Municipality',
       'Pipra Rural Municipality', 'Ramgopalpur Municipality',
       'Samsi Rural Municipality', 'Sonama Rural Municipality',
       'Bagmati Municipality', 'Balara Municipality',
       'Barahathawa Municipality', 'Basbariya Rural Municipality',
       'Bishnu Rural Municipality', 'Bramhapuri Rural Municipality',
       'Chakraghatta Rural Municipality',
       'Chandranagar Rural Municipality', 'Dhankaul Rural Municipality',
       'Godaita Municipality', 'Haripur Municipality',
       'Haripurwa Municipality', 'Hariwan Municipality',
       'Ishworpur Municipality', 'Kabilasi Municipality',
       'Kaudena Rural Municipality', 'Lalbandi Municipality',
       'Malangawa Municipality', 'Parsa Rural Municipality',
       'Ramnagar Rural Municipality', 'Baudhimai Municipality',
       'Brindaban Municipality', 'Chandrapur Municipality',
       'Dewahhi Gonahi Municipality', 'Durga Bhagwati Rural Municipality',
       'Gadhimai Municipality', 'Garuda Municipality',
       'Gaur Municipality', 'Gujara Municipality',
       'Ishanath Municipality', 'Katahariya Municipality',
       'Madhav Narayan Municipality', 'Maulapur Municipality',
       'Paroha Municipality', 'Phatuwa Bijayapur Municipality',
       'Rajdevi Municipality', 'Rajpur Municipality',
       'Yemunamai Rural Municipality', 'Adarshkotwal Rural Municipality',
       'Baragadhi Rural Municipality', 'Bishrampur Rural Municipality',
       'Devtal Rural Municipality',
       'Jitpur Simara Sub-Metropolitian City',
       'Kalaiya Sub-Metropolitian City', 'Karaiyamai Rural Municipality',
       'Kolhabi Municipality', 'Mahagadhimai Municipality',
       'Nijgadh Municipality', 'Pacharauta Municipality',
       'Parwanipur Rural Municipality', 'Pheta Rural Municipality',
       'Prasauni Rural Municipality', 'Simraungadh Municipality',
       'Suwarna Rural Municipality', 'Bahudaramai Municipality',
       'Bindabasini Rural Municipality', 'Birgunj Metropolitian City',
       'Chhipaharmai Rural Municipality', 'Dhobini Rural Municipality',
       'Jagarnathpur Rural Municipality',
       'Jirabhawani Rural Municipality', 'Kalikamai Rural Municipality',
       'Pakahamainpur Rural Municipality', 'Parsagadhi Municipality',
       'Paterwasugauli Rural Municipality', 'Pokhariya Municipality',
       'SakhuwaPrasauni Rural Municipality', 'Thori Rural Municipality',
       'Dudhouli Municipality', 'Ghanglekh Rural Municipality',
       'Golanjor Rural Municipality',
       'Hariharpurgadhi Rural Municipality', 'Kamalamai Municipality',
       'Marin Rural Municipality', 'Phikkal Rural Municipality',
       'Tinpatan Rural Municipality', 'Doramba Rural Municipality',
       'Gokulganga Rural Municipality', 'Khadadevi Rural Municipality',
       'Likhu Tamakoshi Rural Municipality', 'Manthali Municipality',
       'Ramechhap Municipality', 'Sunapati Rural Municipality',
       'Umakunda Rural Municipality', 'Baiteshwor Rural Municipality',
       'Bhimeshwor Municipality', 'Bigu Rural Municipality',
       'Gaurishankar Rural Municipality', 'Jiri Municipality',
       'Kalinchok Rural Municipality', 'Melung Rural Municipality',
       'Sailung Rural Municipality', 'Tamakoshi Rural Municipality',
       'Barhabise Municipality', 'Balefi Rural Municipality',
       'Bhotekoshi Rural Municipality',
       'Chautara SangachokGadhi Municipality',
       'Helambu Rural Municipality', 'Indrawati Rural Municipality',
       'Jugal Rural Municipality', 'Lisangkhu Pakhar Rural Municipality',
       'Melamchi Municipality',
       'Panchpokhari Thangpal Rural Municipality',
       'Tripurasundari Rural Municipality', 'Banepa Municipality',
       'Bethanchowk Rural Municipality', 'Bhumlu Rural Municipality',
       'Chaurideurali Rural Municipality', 'Dhulikhel Municipality',
       'Khanikhola Rural Municipality', 'Mahabharat Rural Municipality',
       'Mandandeupur Municipality', 'Namobuddha Municipality',
       'Panauti Municipality', 'Panchkhal Municipality',
       'Roshi Rural Municipality', 'Temal Rural Municipality',
       'Bagmati Rural Municipality', 'Godawari Municipality',
       'Konjyosom Rural Municipality', 'Lalitpur Metropolitian City',
       'Mahankal Rural Municipality', 'Bhaktapur Municipality',
       'Changunarayan Municipality', 'Madhyapur Thimi Municipality',
       'Suryabinayak Municipality', 'Budhanilakantha Municipality',
       'Chandragiri Municipality', 'Dakshinkali Municipality',
       'Gokarneshwor Municipality', 'Kageshwori Manahora Municipality',
       'Kathmandu Metropolitian City', 'Kirtipur Municipality',
       'Nagarjun Municipality', 'Shankharapur Municipality',
       'Tarakeshwor Municipality', 'Tokha Municipality',
       'Belkotgadhi Municipality', 'Bidur Municipality',
       'Dupcheshwar Rural Municipality', 'Kakani Rural Municipality',
       'Kispang Rural Municipality', 'Myagang Rural Municipality',
       'Panchakanya Rural Municipality', 'Shivapuri Rural Municipality',
       'Suryagadhi Rural Municipality', 'Tadi Rural Municipality',
       'Tarkeshwar Rural Municipality', 'Gosaikunda Rural Municipality',
       'Kalika Rural Municipality', 'Naukunda Rural Municipality',
       'Amachodingmo Rural Municipality', 'Uttargaya Rural Municipality',
       'Benighat Rorang Rural Municipality', 'Dhunibesi Municipality',
       'Gajuri Rural Municipality', 'Galchi Rural Municipality',
       'Gangajamuna Rural Municipality', 'Jwalamukhi Rural Municipality',
       'Khaniyabash Rural Municipality',
       'Netrawati Dabjong Rural Municipality', 'Nilakantha Municipality',
       'Rubi Valley Rural Municipality', 'Siddhalek Rural Municipality',
       'Thakre Rural Municipality', 'Tripura Sundari Rural Municipality',
       'Bakaiya Rural Municipality', 'Bhimphedi Rural Municipality',
       'Hetauda Sub-Metropolitian City',
       'Indrasarowar Rural Municipality', 'Kailash Rural Municipality',
       'Makawanpurgadhi Rural Municipality',
       'Manahari Rural Municipality', 'Raksirang Rural Municipality',
       'Thaha Municipality', 'Bharatpur Metropolitian City',
       'Ichchhyakamana Rural Municipality', 'Kalika Municipality',
       'Khairahani Municipality', 'Rapti Municipality',
       'Ratnanagar Municipality', 'Aarughat Rural Municipality',
       'Ajirkot Rural Municipality', 'Bhimsenthapa Rural Municipality',
       'Chum Nubri Rural Municipality', 'Dharche Rural Municipality',
       'Gandaki Rural Municipality', 'Gorkha Municipality',
       'Palungtar Municipality', 'Sahid Lakhan Rural Municipality',
       'Siranchok Rural Municipality',
       'Barpak Sulikot Rural Municipality', 'Besishahar Municipality',
       'Dordi Rural Municipality', 'Dudhpokhari Rural Municipality',
       'Kwholasothar Rural Municipality', 'MadhyaNepal Municipality',
       'Marsyangdi Rural Municipality', 'Rainas Municipality',
       'Sundarbazar Municipality', 'Anbukhaireni Rural Municipality',
       'Bandipur Rural Municipality', 'Bhanu Municipality',
       'Bhimad Municipality', 'Byas Municipality',
       'Devghat Rural Municipality', 'Ghiring Rural Municipality',
       'Myagde Rural Municipality', 'Rhishing Rural Municipality',
       'Shuklagandaki Municipality', 'Aandhikhola Rural Municipality',
       'Arjunchaupari Rural Municipality', 'Bhirkot Municipality',
       'Biruwa Rural Municipality', 'Chapakot Municipality',
       'Galyang Municipality', 'Harinas Rural Municipality',
       'Kaligandagi Rural Municipality', 'Phedikhola Rural Municipality',
       'Putalibazar Municipality', 'Waling Municipality',
       'Annapurna Rural Municipality',
       'Machhapuchchhre Rural Municipality', 'Madi Rural Municipality',
       'Pokhara Metropolitian City', 'Rupa Rural Municipality',
       'Chame Rural Municipality', 'Narpa Bhumi Rural Municipality',
       'Narshon Rural Municipality',
       'Manang Ingshyang Rural Municipality',
       'Waragung Muktikhsetra Rural Municipality',
       'Lo-Ghekar Damodarkunda Rural Municipality',
       'Gharapjhong Rural Municipality', 'Lomanthang Rural Municipality',
       'Thasang Rural Municipality', 'Beni Municipality',
       'Dhaulagiri Rural Municipality', 'Malika Rural Municipality',
       'Mangala Rural Municipality', 'Raghuganga Rural Municipality',
       'Bihadi Rural Municipality', 'Jaljala Rural Municipality',
       'Kushma Municipality', 'Mahashila Rural Municipality',
       'Modi Rural Municipality', 'Painyu Rural Municipality',
       'Phalebas Municipality', 'Badigad Rural Municipality',
       'Baglung Municipality', 'Bareng Rural Municipality',
       'Dhorpatan Municipality', 'Galkot Municipality',
       'Jaimuni Municipality', 'Kanthekhola Rural Municipality',
       'Nisikhola Rural Municipality', 'Taman Khola Rural Municipality',
       'Tara Khola Rural Municipality',
       'Binayee Tribeni Rural Municipality',
       'Bulingtar Rural Municipality', 'Baudeekali Rural Municipality',
       'Devchuli Municipality', 'Gaidakot Municipality',
       'Hupsekot Rural Municipality', 'Kawasoti Municipality',
       'Madhyabindu Municipality', 'Chandrakot Rural Municipality',
       'Chatrakot Rural Municipality', 'Dhurkot Rural Municipality',
       'Gulmidarbar Rural Municipality', 'Isma Rural Municipality',
       'Kaligandaki Rural Municipality', 'Madane Rural Municipality',
       'Musikot Municipality', 'Resunga Municipality',
       'Ruru Rural Municipality', 'Satyawati Rural Municipality',
       'Bagnaskali Rural Municipality', 'Mathagadhi Rural Municipality',
       'Nisdi Rural Municipality', 'Purbakhola Rural Municipality',
       'Rainadevi Chhahara Rural Municipality',
       'Rambha Rural Municipality', 'Rampur Municipality',
       'Ribdikot Rural Municipality', 'Tansen Municipality',
       'Tinau Rural Municipality', 'Bardaghat Municipality',
       'Palhi Nandan Rural Municipality', 'Pratappur Rural Municipality',
       'Ramgram Municipality', 'Sarawal Rural Municipality',
       'Sunwal Municipality', 'Susta Rural Municipality',
       'Butwal Sub-Metropolitian City', 'Devdaha Municipality',
       'Gaidahawa Rural Municipality', 'Kanchan Rural Municipality',
       'Kotahimai Rural Municipality', 'Lumbini Sanskritik Municipality',
       'Marchawari Rural Municipality', 'Mayadevi Rural Municipality',
       'Omsatiya Rural Municipality', 'Rohini Rural Municipality',
       'Sainamaina Municipality', 'Sammarimai Rural Municipality',
       'Siddharthanagar Municipality', 'Siyari Rural Municipality',
       'Sudhdhodhan Rural Municipality', 'Tillotama Municipality',
       'Banganga Municipality', 'Bijayanagar Rural Municipality',
       'Buddhabhumi Municipality', 'Kapilbastu Municipality',
       'Krishnanagar Municipality', 'Maharajgunj Municipality',
       'Shivaraj Municipality', 'Suddhodhan Rural Municipality',
       'Yashodhara Rural Municipality', 'Bhumekasthan Municipality',
       'Chhatradev Rural Municipality', 'Malarani Rural Municipality',
       'Panini Rural Municipality', 'Sandhikharka Municipality',
       'Sitganga Municipality', 'Ayirabati Rural Municipality',
       'Gaumukhi Rural Municipality', 'Jhimruk Rural Municipality',
       'Mallarani Rural Municipality', 'Mandavi Rural Municipality',
       'Naubahini Rural Municipality', 'Pyuthan Municipality',
       'Sarumarani Rural Municipality', 'Sworgadwary Municipality',
       'Pariwartan Rural Municipality', 'Lungri Rural Municipality',
       'Rolpa Municipality', 'Runtigadi Rural Municipality',
       'Sunil Smriti Rural Municipality', 'Gangadev Rural Municipality',
       'Sunchhahari Rural Municipality', 'Thawang Rural Municipality',
       'Tribeni Rural Municipality', 'Bhume Rural Municipality',
       'Putha Uttarganga Rural Municipality', 'Sisne Rural Municipality',
       'Babai Rural Municipality', 'Banglachuli Rural Municipality',
       'Dangisharan Rural Municipality', 'Gadhawa Rural Municipality',
       'Ghorahi Sub-Metropolitian City', 'Lamahi Municipality',
       'Rajpur Rural Municipality', 'Rapti Rural Municipality',
       'Shantinagar Rural Municipality',
       'Tulsipur Sub-Metropolitian City', 'Baijanath Rural Municipality',
       'Duduwa Rural Municipality', 'Janki Rural Municipality',
       'Khajura Rural Municipality', 'Kohalpur Municipality',
       'Narainapur Rural Municipality',
       'Nepalgunj Sub-Metropolitian City',
       'Rapti Sonari Rural Municipality',
       'Badhaiyatal Rural Municipality', 'Bansagadhi Municipality',
       'Barbardiya Municipality', 'Geruwa Rural Municipality',
       'Gulariya Municipality', 'Madhuwan Municipality',
       'Rajapur Municipality', 'Thakurbaba Municipality',
       'Aathbiskot Municipality', 'Banfikot Rural Municipality',
       'Chaurjahari Municipality', 'Sani Bheri Rural Municipality',
       'Bagchaur Municipality', 'Bangad Kupinde Municipality',
       'Chhatreshwori Rural Municipality', 'Darma Rural Municipality',
       'Siddha Kumakh Rural Municipality', 'Kalimati Rural Municipality',
       'Kapurkot Rural Municipality', 'Kumakh Rural Municipality',
       'Sharada Municipality', 'Barahtal Rural Municipality',
       'Bheriganga Municipality', 'Birendranagar Municipality',

In [24]:
len(data['Local Level Name'].unique())

737

In [25]:
data['Local Level Name'].nunique()

737

737 unique Local level names.

3. Are there any missing values or duplicate rows in the dataset?

In [26]:
data.isnull().sum()

_id                       0
District                  0
Local Level Name          0
Total family number       0
Total household number    0
Total population          0
Total Male                0
Total Female              0
dtype: int64

No, there is no any missing values

In [27]:
data.duplicated().sum()

np.int64(0)

No, their are no duplicate rows.

4. What is the summary statistics (mean, median, min, max, std) for numerical columns like Total Population, Total Male, Total Female, etc.?

In [28]:
data.describe()

,_id,Total family number,Total household number,Total population,Total Male,Total Female
count,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000
mean,377.000000,8976.723772,7493.590969,38612.204515,18842.814077,19769.390438
std,217.516666,12986.552238,8401.892705,49904.377212,24891.928559,25046.362147
min,1.000000,125.000000,125.000000,398.000000,170.000000,228.000000
25%,189.000000,4036.000000,3653.000000,16768.000000,8115.000000,8553.000000
50%,377.000000,5896.000000,5195.000000,25508.000000,12248.000000,13010.000000
75%,565.000000,9510.000000,8151.000000,44929.000000,22100.000000,23068.000000
max,753.000000,231714.000000,105649.000000,845767.000000,431501.000000,414266.000000

5. What is the range and distribution of Total Family Number and Total Household Number?

In [35]:
# to find range 
min_family_num = data['Total family number'].min()
max_family_num = data['Total family number'].max()
family_range = max_family_num - min_family_num
print(f"Range of Total family number = {family_range}")

min_household = data['Total household number'].min()
max_household = data['Total household number'].max()
household_range = max_household - min_household
print(f"Range of Total household number = {household_range}")

Range of Total family number = 231589
Range of Total household number = 105524

In [36]:
# to find distribution
data['Total family number'].describe()

count       753.000000
mean       8976.723772
std       12986.552238
min         125.000000
25%        4036.000000
50%        5896.000000
75%        9510.000000
max      231714.000000
Name: Total family number, dtype: float64

In [37]:
data["Total household number"].describe()

count       753.000000
mean       7493.590969
std        8401.892705
min         125.000000
25%        3653.000000
50%        5195.000000
75%        8151.000000
max      105649.000000
Name: Total household number, dtype: float64